import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navigation from "../components/ui/navigation";


import "./globals.css";

// Load custom Google fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Page metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout wraps every page
export default function RootLayout({
  children, // This will be replaced by the content of each individual page
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Navigation bar at the top appears on all pages */}
        <Navigation/>

        {/* Page-specific content gets injected here */}
        {children}

        {/* Footer appears on all pages */}
        <footer className="bg-slate-900 text-white p-4 text-center">
          Devesh
        </footer>
      </body>
    </html>
  );
}
